story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story10.urls')),
]

story10/urls.py
from django.urls import path
from .views import *

app_name='story10'
urlpatterns = [
    path('', index, name='index'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('signup/', signup_user, name='signup'),
]

story10/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profileImage = models.URLField()

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

story10/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile
from django.contrib.auth.forms import UserCreationForm

class SignUpForm(UserCreationForm):
    image = forms.URLField(required=True)
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2', 'image')

story10/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from .forms import *

# Create your views here.
def index(request):
    return render(request, 'index.html')

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        user_dict = {'username':username, 'password':password}
        if user is not None:
            login(request, user)
            return redirect('/')
        
        else:
            message = {'message':'Invalid username or password'}
            return render(request, 'login.html', message)
    
    else :
        return render(request, 'login.html')

def logout_user(request):
    request.session.flush()
    logout(request)
    return redirect('/')

def signup_user(request):
    if request.method == "POST":
        form = SignUpForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.profile.profileImage = form.cleaned_data.get('image')
            user.save()
            return redirect('/login/')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form' : form})

story10/templates/index.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <style>
      html, body {
        width: 100%;
        height: 100%;
        margin: 0;
        padding: 0;
        overflow-x: hidden;
        background-color: #D7DDE8;
      }
      .btn {
        background-color: #D7DDE8;
        color: #757F9A;
        border-radius: 20px;
        border-color: transparent;
        box-shadow: -3px -3px 3px 0 rgba(255,255,255, 0.7), 3px 3px 3px 0 rgba(0,0,0,0.2);
      }
      .btn:hover, .btn:active {
        font-weight: bold;
        color: #222;
        box-shadow: inset -3px -3px 3px 0 rgba(255,255,255, 0.7), inset 3px 3px 3px 0 rgba(0,0,0,0.2);
      }
    </style>

    <!-- FONT -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,500,600,700,800,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Spartan:400,600,700&display=swap" rel="stylesheet">

    {% if user.is_authenticated %}
      <title>Welcome, {{ request.user }}!</title>
    {% else %}
      <title>Welcome, User!</title>
    {% endif %}

  </head>
  <body>
    <div style="margin-top: 200px;">
      <div class="row-lg-12 text-center mb-5" style="padding-left: 120px; padding-right:120px;">
          {% if user.is_authenticated %}
          <h1 class="title text-center" style="font-family: 'Playfair Display'; margin-top: 80px; font-size: 60px; font-weight: bold; color: #757F9A;" id="welcome">Welcome, {{ request.user }}!</h1>
          <img src="{{user.profile.profileImage}}" class="img-fluid">
          <a href="logout/"><button type="submit" class="btn align-middle" id="logOut" style="width: 100px; margin:20px;">Log Out</button></a>
          {% else %}
          <h1 class="title text-center" style="font-family: 'Playfair Display'; margin-top: 80px; font-size: 60px; font-weight: bold; color: #757F9A;" id="welcome">Welcome, User!</h1>
          <a href="login/"><button type="submit" class="btn align-middle" id="logIn" style="width: 100px; margin:20px;">Log In</button></a>
          <br>
          <a href="signup/"><button type="submit" class="btn align-middle" id="signUp" style="width: 100px;">Sign Up</button></a>
          {% endif %}
      </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"   integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30="   crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

story10/templates/login.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- CSS Style -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" media="screen"/>

    <style>
      html, body {
        width: 100%;
        height: 100%;
        margin: 0;
        padding: 0;
        overflow-x: hidden;
      }
    </style>
    
    <!-- FONT -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,500,600,700,800,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Spartan:400,600,700&display=swap" rel="stylesheet">
  
    <title>Log In</title>
  </head>
  <body>

    <div id="welcome">
      <div class="row one" style="margin-top:14%;">
        <div class="col-md-6">
          <h1 class="text" id="top">Hello user, <br>how are you?</h1>
          <h1 class="text" id="mid">Hola, como estas?</h1>
          <h1 class="text" id="bottom">Salut, comment allez-vous?</h1>
        </div>
        <div class="col-md-6">
          <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <h1 class="invalid">{{message}}</h1>
                <h1 class="text">Username:</h1>
                <input type="text" class="form-control" id="username" name="username" maxlength="40" placeholder="Username">
                <h1 class="text">Password</h1>
                <input type="password" class="form-control" id="password" name="password" maxlength="40" placeholder="Password">
                <button type="submit" class="btn" id="logIn" name="logIn">Log In</button>
                <a href="/signup/" class="btn align-middle" id="signUp" style="width: 100px;">Sign Up</a>
            </div>
          </form>
        </div>
      </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"   integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30="   crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

story10/templates/signup.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <style>
        html, body {
            width: 100%;
            height: 100%;
            margin: 0;
            padding: 0;
            overflow-x: hidden;
            background-color: #D7DDE8;
        }
        .btn {
            width: 100px;
            background-color: #D7DDE8;
            color: #757F9A;
            border-radius: 20px;
            border-color: transparent;
            box-shadow: -3px -3px 3px 0 rgba(255,255,255, 0.7), 3px 3px 3px 0 rgba(0,0,0,0.2);
        }
        .btn:hover, .btn:active {
            font-weight: bold;
            color: #222;
            box-shadow: inset -3px -3px 3px 0 rgba(255,255,255, 0.7), inset 3px 3px 3px 0 rgba(0,0,0,0.2);
        }
        label{
            font-weight: bold;
        }
        
        input{
            padding: 5px;
            padding-left:15px;
            width: 600px;
            background-color: #434343;
            /* border: 0; */
            /* outline: 0; */
            border: none;
            border-radius: 30px;
            font-size: 20px;
            color: #EEE;
        }
        #id_username {
            margin-left: 130px;
        }
        #id_email{
            margin-left: 100px;
        }
        #id_first_name {
            margin-left: 128px;
        }
        #id_last_name {
            margin-left: 130px;
        }
        #id_password1 {
            margin-left: 135px;
        }
        #id_password2 {
            margin-left: 30px;
        }
        #id_image {
            margin-left: 160px;
        }
        ul li {
            margin-left: 215px;
        }
        span{
            margin-left: 230px;
        }
        
    </style>

    <!-- FONT -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,500,600,700,800,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Spartan:400,600,700&display=swap" rel="stylesheet">

    <title>Sign Up</title>

  </head>
  <body>
    <div style="margin: 100px; margin-top: 0;">
      <div class="row-lg-12 mb-5" style="padding-left: 120px; padding-right:120px;">
        <h1 style="font-family: 'Playfair Display'; margin-top: 50px; font-size: 60px; font-weight: bold; color: #757F9A;">Create a new account</h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <a href="login/"><button class="btn" id="signUp">Sign Up</button></a>
        </form>
      </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"   integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30="   crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>